
    const database = [
    // --- DOMANDE PRECEDENTI ---
    { id: "31029", argomento: "Distrazione", testo: "Utilizzare il cellulare alla guida, anche se con impianto viva-voce, può ridurre l’attenzione alla strada", immagine: "", rispostaCorretta: true },
    { id: "31030", argomento: "Distrazione", testo: "La distrazione durante la guida è una delle principali cause di incidenti stradali", immagine: "", rispostaCorretta: true },
    { id: "31031", argomento: "Stato Conducente", testo: "L’attenzione alla guida diminuisce quando si è affaticati", immagine: "", rispostaCorretta: true },
    { id: "31032", argomento: "Distrazione", testo: "Impostare il navigatore satellitare mentre si guida riduce l’attenzione alla strada", immagine: "", rispostaCorretta: true },
    { id: "31033", argomento: "Stato Conducente", testo: "Si può 'allenare' l’attenzione alla guida", immagine: "", rispostaCorretta: true },
    { id: "31034", argomento: "Stato Conducente", testo: "I nostri sensi non riescono a cogliere tutti gli stimoli presenti nell’ambiente", immagine: "", rispostaCorretta: true },
    { id: "31035", argomento: "Stato Conducente", testo: "Le emozioni influenzano la nostra attenzione", immagine: "", rispostaCorretta: true },
    { id: "31036", argomento: "Stato Conducente", testo: "A volte ci si espone a situazioni più rischiose di quelle che si è in grado di gestire", immagine: "", rispostaCorretta: true },
    { id: "31037", argomento: "Distrazione", testo: "Il conducente può distogliere lo sguardo dalla strada quando ritiene che non ci sia pericolo imminente", immagine: "", rispostaCorretta: false },
    { id: "31038", argomento: "Distrazione", testo: "In prossimità di un incrocio si può inviare un rapido messaggio con il cellulare durante l'attesa", immagine: "", rispostaCorretta: false },

    // --- NUOVE DOMANDE (FALSO) ---
    { id: "31039", argomento: "Norme di Circolazione", testo: "Il conducente che intende passare per primo in un incrocio deve sopraggiungervi più velocemente", immagine: "", rispostaCorretta: false },
    { id: "31040", argomento: "Distrazione", testo: "Qualora non vi sia pericolo imminente, si può comporre un numero di telefono senza fermarsi", immagine: "", rispostaCorretta: false },
    { id: "31041", argomento: "Stato Conducente", testo: "Il comportamento degli altri utenti della strada è ininfluente per una guida sicura", immagine: "", rispostaCorretta: false },
    { id: "31042", argomento: "Stato Conducente", testo: "Il conducente può non tenere conto del comportamento degli altri utenti se questi non rispettano le regole", immagine: "", rispostaCorretta: false },
    { id: "31043", argomento: "Stato Conducente", testo: "La percezione di un pericolo e la reazione non sono influenzate dalle condizioni ambientali", immagine: "", rispostaCorretta: false },
    { id: "31044", argomento: "Stato Conducente", testo: "Un conducente deve sempre sottostimare le situazioni di pericolo per non farsi travolgere dall'ansia", immagine: "", rispostaCorretta: false },
    { id: "31045", argomento: "Stato Conducente", testo: "Il conducente deve accogliere gli inviti dei passeggeri a guidare più velocemente", immagine: "", rispostaCorretta: false },
    { id: "31046", argomento: "Stato Conducente", testo: "Il conducente deve concentrarsi prevalentemente sul tratto di strada non superiore a tre metri antistante il veicolo", immagine: "", rispostaCorretta: false },
    { id: "31047", argomento: "Distrazione", testo: "Mentre il veicolo è in marcia, il conducente può programmare il navigatore in qualsiasi momento", immagine: "", rispostaCorretta: false },
    { id: "31048", argomento: "Norme di Circolazione", testo: "Lo specchio retrovisore destro deve essere utilizzato solo da conducenti esperti", immagine: "", rispostaCorretta: false },
    { id: "31049", argomento: "Norme di Circolazione", testo: "Gli specchi retrovisori devono essere regolati mentre il veicolo è in movimento", immagine: "", rispostaCorretta: false },
    { id: "31050", argomento: "Norme di Circolazione", testo: "Il rispetto delle norme è importante solo se la violazione comporta una sanzione elevata", immagine: "", rispostaCorretta: false },
    { id: "31051", argomento: "Norme di Circolazione", testo: "Il rispetto delle norme è importante per gli utenti deboli, ma non per i conducenti di autoveicoli", immagine: "", rispostaCorretta: false },
    { id: "31052", argomento: "Norme di Circolazione", testo: "Il rispetto delle norme è importante nel traffico intenso, ma non con circolazione scorrevole", immagine: "", rispostaCorretta: false },
    { id: "31053", argomento: "Norme di Circolazione", testo: "Il divieto di sorpasso può non essere osservato se si è in coda dietro a un veicolo lento da più di 10 minuti", immagine: "", rispostaCorretta: false },
    { id: "31054", argomento: "Norme di Circolazione", testo: "Il rispetto della posizione sulla carreggiata è una norma secondaria che può non essere osservata", immagine: "", rispostaCorretta: false },
    { id: "31055", argomento: "Distrazione", testo: "L’attenzione alla guida è importante solo quando si compiono manovre pericolose come il sorpasso", immagine: "", rispostaCorretta: false },
    { id: "31056", argomento: "Stato Conducente", testo: "Bere un liquore ad alta gradazione migliora l’attenzione dopo circa 10 minuti", immagine: "", rispostaCorretta: false },
    { id: "31057", argomento: "Distrazione", testo: "Sintonizzare manualmente l’autoradio non comporta perdita di attenzione perché è un'abitudine", immagine: "", rispostaCorretta: false },
    { id: "31058", argomento: "Stato Conducente", testo: "Se si è in stato di ebbrezza lieve, si riesce a guidare comunque in sicurezza", immagine: "", rispostaCorretta: false },
    { id: "31059", argomento: "Stato Conducente", testo: "La quantità di attenzione che si può prestare alla strada mentre si guida è illimitata", immagine: "", rispostaCorretta: false },
    { id: "31060", argomento: "Stato Conducente", testo: "Con 0,5 grammi per litro di alcool nel sangue si riesce a concentrarsi meglio", immagine: "", rispostaCorretta: false },
    { id: "31061", argomento: "Stato Conducente", testo: "I nostri sensi riescono a cogliere tutti gli stimoli presenti nell’ambiente", immagine: "", rispostaCorretta: false },
    { id: "31062", argomento: "Stato Conducente", testo: "I nostri sensi sono in grado di percepire stimoli di qualunque intensità", immagine: "", rispostaCorretta: false },
    { id: "31063", argomento: "Stato Conducente", testo: "In condizioni di traffico intenso lo stress può aiutare il conducente a mantenersi vigile", immagine: "", rispostaCorretta: false },
    { id: "31064", argomento: "Stato Conducente", testo: "L’udito non è un senso importante quando si guida", immagine: "", rispostaCorretta: false },

    // --- NUOVE DOMANDE (VERO) ---
    { id: "31011", argomento: "Distrazione", testo: "Distrarsi alla guida può causare incidenti stradali con gravi conseguenze", immagine: "", rispostaCorretta: true },
    { id: "31012", argomento: "Norme di Circolazione", testo: "Quando si attraversa un incrocio è necessario mantenere la massima concentrazione", immagine: "", rispostaCorretta: true },
    { id: "31013", argomento: "Distrazione", testo: "E’ pericoloso distogliere lo sguardo dalla strada anche per pochi millisecondi", immagine: "", rispostaCorretta: true },
    { id: "31014", argomento: "Stato Conducente", testo: "Per prevenire incidenti, il conducente deve valutare il comportamento degli altri utenti", immagine: "", rispostaCorretta: true },
    { id: "31015", argomento: "Stato Conducente", testo: "La percezione di un pericolo e la reazione del conducente sono influenzate dalle condizioni ambientali", immagine: "", rispostaCorretta: true },
    { id: "31016", argomento: "Stato Conducente", testo: "L’ansia può ridurre la capacità di prestare attenzione ai pericoli", immagine: "", rispostaCorretta: true },
    { id: "31017", argomento: "Stato Conducente", testo: "Un conducente deve considerare che non sempre è in grado di valutare correttamente le proprie capacità", immagine: "", rispostaCorretta: true },
    { id: "31018", argomento: "Distrazione", testo: "La capacità di attenzione può essere influenzata dall'ascolto di musica a volume molto alto", immagine: "", rispostaCorretta: true },
    { id: "31019", argomento: "Distrazione", testo: "Parlare animosamente con altre persone a bordo può influenzare negativamente la guida", immagine: "", rispostaCorretta: true },
    { id: "31020", argomento: "Norme di Circolazione", testo: "Se non si è certi di passare in sicurezza un incrocio, è necessario arrestarsi e attendere", immagine: "", rispostaCorretta: true },
    { id: "31021", argomento: "Distrazione", testo: "La presenza di passeggeri che schiamazzano può influenzare la concentrazione del conducente", immagine: "", rispostaCorretta: true },
    { id: "31022", argomento: "Stato Conducente", testo: "Il conducente deve prestare attenzione sia agli utenti davanti che a quelli ai bordi della strada", immagine: "", rispostaCorretta: true },
    { id: "31023", argomento: "Distrazione", testo: "Concentrare l’attenzione sulle indicazioni del navigatore può rappresentare un elemento di distrazione", immagine: "", rispostaCorretta: true },
    { id: "31024", argomento: "Stato Conducente", testo: "Il conducente non deve mai sopravvalutare la propria abilità di guida", immagine: "", rispostaCorretta: true },
    { id: "31025", argomento: "Norme di Circolazione", testo: "Le norme di circolazione garantiscono una maggior sicurezza per tutti gli utenti", immagine: "", rispostaCorretta: true },
    { id: "31026", argomento: "Norme di Circolazione", testo: "Il rispetto delle norme permette di limitare i rischi per tutti i veicoli, a motore e non", immagine: "", rispostaCorretta: true },
    { id: "31027", argomento: "Norme di Circolazione", testo: "Il rispetto delle norme permette di limitare l’intralcio alla circolazione", immagine: "", rispostaCorretta: true },
    { id: "31028", argomento: "Distrazione", testo: "Utilizzare il cellulare alla guida è pericoloso perché riduce l’attenzione alla strada", immagine: "", rispostaCorretta: true },
    // --- BLOCCO: STERZO (25386 - 25403) ---
    { id: "25386", argomento: "Sterzo", testo: "In caso di mal funzionamento del servosterzo, lo sterzo diventa 'pesante'", immagine: "", rispostaCorretta: true },
    { id: "25387", argomento: "Sterzo", testo: "In caso di foratura di un pneumatico, lo sterzo tira nella direzione della ruota forata", immagine: "", rispostaCorretta: true },
    { id: "25388", argomento: "Sterzo", testo: "Al fine di garantire la sicurezza della circolazione occorre verificare periodicamente l'assenza di giochi anomali allo sterzo", immagine: "", rispostaCorretta: true },
    { id: "25389", argomento: "Sterzo", testo: "La 'durezza' dello sterzo può essere indice di insufficiente pressione dei pneumatici", immagine: "", rispostaCorretta: true },
    { id: "25390", argomento: "Sterzo", testo: "Il servosterzo idraulico non funziona se il motore è spento", immagine: "", rispostaCorretta: true },
    { id: "25391", argomento: "Sterzo", testo: "Eccessivi giochi allo sterzo rendono imprecisa la traiettoria del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25392", argomento: "Sterzo", testo: "La convergenza delle ruote ha influenza sulla precisione della sterzata", immagine: "", rispostaCorretta: true },
    { id: "25393", argomento: "Sterzo", testo: "Se lo sterzo vibra è bene far controllare la bilanciatura delle ruote anteriori", immagine: "", rispostaCorretta: true },
    { id: "25394", argomento: "Sterzo", testo: "Il servosterzo aiuta a controllare la traiettoria del veicolo in caso di foratura di un pneumatico", immagine: "", rispostaCorretta: true },
    { id: "25395", argomento: "Sterzo", testo: "Il servosterzo migliora l'azione frenante del veicolo", immagine: "", rispostaCorretta: false },
    { id: "25396", argomento: "Sterzo", testo: "In caso di foratura di un pneumatico, lo sterzo tira nella direzione opposta a quella della ruota forata", immagine: "", rispostaCorretta: false },
    { id: "25397", argomento: "Sterzo", testo: "Se lo sterzo vibra si deve far controllare la bilanciatura delle ruote posteriori", immagine: "", rispostaCorretta: false },
    { id: "25398", argomento: "Sterzo", testo: "La rottura del servosterzo si manifesta con un'eccessiva facilità di manovra dello sterzo", immagine: "", rispostaCorretta: false },
    { id: "25399", argomento: "Sterzo", testo: "Il volante deve essere impugnato nella sua parte bassa, con entrambe le mani sotto le razze", immagine: "", rispostaCorretta: false },
    { id: "25400", argomento: "Sterzo", testo: "Il volante non può essere regolato in altezza", immagine: "", rispostaCorretta: false },
    { id: "25401", argomento: "Sterzo", testo: "La precisione della sterzata non è influenzata dalle cattive condizioni delle sospensioni e degli ammortizzatori", immagine: "", rispostaCorretta: false },
    { id: "25402", argomento: "Sterzo", testo: "La precisione della sterzata è influenzata dalla scarsa pressione dell'olio di lubrificazione", immagine: "", rispostaCorretta: false },
    { id: "25403", argomento: "Sterzo", testo: "La precisione della sterzata è influenzata dall'eccessiva temperatura del liquido di raffreddamento", immagine: "", rispostaCorretta: false },

    // --- BLOCCO: IMPIANTO DI SCARICO (25404 - 25417) ---
    { id: "25404", argomento: "Impianto di Scarico", testo: "La marmitta deteriorata aumenta l'inquinamento acustico prodotto dai veicoli a motore", immagine: "", rispostaCorretta: true },
    { id: "25405", argomento: "Impianto di Scarico", testo: "La marmitta deteriorata deve essere sostituita con altra di tipo approvato per quel tipo di veicolo", immagine: "", rispostaCorretta: true },
    { id: "25406", argomento: "Impianto di Scarico", testo: "L'impianto di scarico ha lo scopo di convogliare i gas di scarico verso l'esterno dopo averne abbassato la tossicità", immagine: "", rispostaCorretta: true },
    { id: "25407", argomento: "Impianto di Scarico", testo: "L'impianto di scarico ha lo scopo di convogliare i gas di scarico verso l'esterno dopo averne abbassato la pressione", immagine: "", rispostaCorretta: true },
    { id: "25408", argomento: "Impianto di Scarico", testo: "L'impianto di scarico ha lo scopo di convogliare i gas di scarico verso l'esterno dopo averne abbassato la temperatura", immagine: "", rispostaCorretta: true },
    { id: "25409", argomento: "Impianto di Scarico", testo: "L'impianto di scarico ha lo scopo di ridurre la rumorosità del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25410", argomento: "Impianto di Scarico", testo: "L'impianto di scarico ha lo scopo di ridurre l'inquinamento atmosferico causato dai gas di scarico del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25411", argomento: "Impianto di Scarico", testo: "L'impianto di scarico deve essere integralmente sostituito a ogni cambio di lubrificante", immagine: "", rispostaCorretta: false },
    { id: "25412", argomento: "Impianto di Scarico", testo: "L'impianto di scarico dei veicoli elettrici necessita di manutenzione più frequente rispetto a quello dei veicoli con motore a scoppio", immagine: "", rispostaCorretta: false },
    { id: "25413", argomento: "Impianto di Scarico", testo: "Fuori dei centri abitati, i veicoli possono circolare anche senza silenziatore", immagine: "", rispostaCorretta: false },
    { id: "25414", argomento: "Impianto di Scarico", testo: "Se il tubo di scarico si fora, lo si può riparare avvolgendolo con lana di vetro e nastro isolante", immagine: "", rispostaCorretta: false },
    { id: "25415", argomento: "Impianto di Scarico", testo: "La sostituzione del tubo di scarico può essere fatta anche personalmente, senza rivolgersi ad un'officina autorizzata", immagine: "", rispostaCorretta: false },
    { id: "25416", argomento: "Impianto di Scarico", testo: "E' possibile modificare l'impianto di scarico, purché si autocertifichi che ciò non comporta aumenti del consumo", immagine: "", rispostaCorretta: false },
    { id: "25417", argomento: "Impianto di Scarico", testo: "La manomissione dell'impianto di scarico non comporta alcuna sanzione, purché si circoli solo nei centri urbani", immagine: "", rispostaCorretta: false },

    // --- BLOCCO: MANUTENZIONE MOTOCICLI E INTERRUTTORI (25419 - 25431) ---
    { id: "25419", argomento: "Manutenzione Motocicli", testo: "Nei veicoli a motore a due ruote è possibile spegnere il motore anche tramite l'interruttore di emergenza posto sul manubrio", immagine: "", rispostaCorretta: true },
    { id: "25420", argomento: "Manutenzione Motocicli", testo: "Nei motocicli, per avviare il motore, è necessario che l'interruttore di emergenza sia su ON/Avviamento", immagine: "", rispostaCorretta: true },
    { id: "25421", argomento: "Manutenzione Motocicli", testo: "Nei motocicli, l'interruttore di emergenza permette lo spegnimento senza staccare le mani dal manubrio", immagine: "", rispostaCorretta: true },
    { id: "25422", argomento: "Manutenzione Motocicli", testo: "L'interruttore di emergenza permette lo spegnimento se ci si arresta su forti pendenze avendo le mani occupate sulle leve", immagine: "", rispostaCorretta: true },
    { id: "25423", argomento: "Manutenzione Motocicli", testo: "L'interruttore di emergenza dei veicoli a due ruote, se guasto, deve essere riparato al più presto", immagine: "", rispostaCorretta: true },
    { id: "25424", argomento: "Manutenzione Motocicli", testo: "Su un motociclo, nelle situazioni ordinarie, è preferibile utilizzare la chiave di accensione anziché l'interruttore di emergenza", immagine: "", rispostaCorretta: true },
    { id: "25425", argomento: "Manutenzione Motocicli", testo: "Nei motocicli, l'interruttore di emergenza posto sul manubrio sostituisce il dispositivo di accensione a chiave", immagine: "", rispostaCorretta: false },
    { id: "25426", argomento: "Manutenzione Motocicli", testo: "I veicoli a due ruote sono equipaggiati di un interruttore d'emergenza posto sulla pedivella del cambio", immagine: "", rispostaCorretta: false },
    { id: "25427", argomento: "Manutenzione Motocicli", testo: "Nei veicoli a due ruote, l'interruttore d'emergenza permette il blocco istantaneo delle ruote", immagine: "", rispostaCorretta: false },
    { id: "25428", argomento: "Manutenzione Motocicli", testo: "L'interruttore di emergenza sul cavalletto laterale serve per spegnere il motore sulle strade in pendenza", immagine: "", rispostaCorretta: false },
    { id: "25429", argomento: "Manutenzione Motocicli", testo: "I veicoli a due ruote sono equipaggiati di un interruttore d'emergenza azionabile con la pressione del piede destro", immagine: "", rispostaCorretta: false },
    { id: "25430", argomento: "Manutenzione Motocicli", testo: "Nei veicoli a due ruote, l'interruttore d'emergenza ha la funzione di freno di stazionamento", immagine: "", rispostaCorretta: false },
    { id: "25431", argomento: "Manutenzione Motocicli", testo: "Nei veicoli a due ruote, l'interruttore d'emergenza è collegato con l'antifurto del veicolo", immagine: "", rispostaCorretta: false },

    // --- BLOCCO: TRASMISSIONE E LIVELLI (25432 - 25454) ---
    { id: "25432", argomento: "Trasmissione e Livelli", testo: "Nei motocicli è opportuno verificare periodicamente l'usura della catena di trasmissione", immagine: "", rispostaCorretta: true },
    { id: "25433", argomento: "Trasmissione e Livelli", testo: "La catena di trasmissione dei motocicli, se non lubrificata, può essere soggetta a rottura", immagine: "", rispostaCorretta: true },
    { id: "25434", argomento: "Trasmissione e Livelli", testo: "Nei motocicli, la catena di trasmissione collega il pignone motore alla corona della ruota", immagine: "", rispostaCorretta: true },
    { id: "25435", argomento: "Trasmissione e Livelli", testo: "E' opportuno verificare periodicamente che la catena di trasmissione sia ben lubrificata", immagine: "", rispostaCorretta: true },
    { id: "25436", argomento: "Trasmissione e Livelli", testo: "Nei motocicli è opportuno verificare periodicamente la corretta tensione della catena di trasmissione", immagine: "", rispostaCorretta: true },
    { id: "25437", argomento: "Trasmissione e Livelli", testo: "La rottura improvvisa della catena può causare il bloccaggio della ruota posteriore e perdita di controllo", immagine: "", rispostaCorretta: true },
    { id: "25438", argomento: "Trasmissione e Livelli", testo: "Nei motocicli, se la catena di trasmissione mostra segni di usura occorre sostituirla", immagine: "", rispostaCorretta: true },
    { id: "25439", argomento: "Trasmissione e Livelli", testo: "La catena di trasmissione non necessita di lubrificazione perché realizzata in acciaio autolubrificante", immagine: "", rispostaCorretta: false },
    { id: "25440", argomento: "Trasmissione e Livelli", testo: "La rottura della catena di trasmissione pregiudica la velocità di marcia, ma non la sicurezza", immagine: "", rispostaCorretta: false },
    { id: "25441", argomento: "Trasmissione e Livelli", testo: "Se la catena mostra segni di usura occorre rinforzarla con filo di ferro di tipo idoneo", immagine: "", rispostaCorretta: false },
    { id: "25442", argomento: "Trasmissione e Livelli", testo: "In caso di sostituzione della catena, non è mai necessario sostituire anche pignone e corona", immagine: "", rispostaCorretta: false },
    { id: "25443", argomento: "Trasmissione e Livelli", testo: "Non è necessario il controllo della tensione della catena perché dotata di tenditore automatico", immagine: "", rispostaCorretta: false },
    { id: "25444", argomento: "Trasmissione e Livelli", testo: "La catena deve essere pulita con sgrassante ma assolutamente non lubrificata per non far slittare il cambio", immagine: "", rispostaCorretta: false },
    { id: "25445", argomento: "Trasmissione e Livelli", testo: "È possibile sostituire pignone e corona in modo da modificare il rapporto di trasmissione", immagine: "", rispostaCorretta: false },
    { id: "25446", argomento: "Trasmissione e Livelli", testo: "Il livello dell'olio deve essere controllato a veicolo perfettamente orizzontale, con le ruote a terra", immagine: "", rispostaCorretta: true },
    { id: "25447", argomento: "Trasmissione e Livelli", testo: "Sui motocicli è necessario verificare periodicamente i livelli di olio motore e liquido freni", immagine: "", rispostaCorretta: true },
    { id: "25448", argomento: "Trasmissione e Livelli", testo: "Sui motocicli, il livello del liquido freni si verifica controllando l'apposita vaschetta trasparente", immagine: "", rispostaCorretta: true },
    { id: "25449", argomento: "Trasmissione e Livelli", testo: "In alcuni motocicli, il livello dell'olio motore si controlla da una finestrella sulla coppa motore", immagine: "", rispostaCorretta: true },
    { id: "25450", argomento: "Trasmissione e Livelli", testo: "Il livello del lubrificante va controllato con veicolo in piano e dopo aver spento il motore da alcuni minuti", immagine: "", rispostaCorretta: true },
    { id: "25451", argomento: "Trasmissione e Livelli", testo: "Sui motocicli non vi sono liquidi di cui controllare i livelli perché i serbatoi sono sigillati", immagine: "", rispostaCorretta: false },
    { id: "25452", argomento: "Trasmissione e Livelli", testo: "Il livello dell'olio deve essere controllato con motore al minimo e moto sul cavalletto", immagine: "", rispostaCorretta: false },
    { id: "25453", argomento: "Trasmissione e Livelli", testo: "I motocicli non hanno serbatoio liquido freni perché la frenatura è di tipo meccanico", immagine: "", rispostaCorretta: false },
    { id: "25454", argomento: "Trasmissione e Livelli", testo: "Sui motocicli raffreddati ad aria, il livello del liquido di raffreddamento si controlla tra le alette", immagine: "", rispostaCorretta: false },
    // --- BLOCCO: SICUREZZA E VISIBILITÀ (25282 - 25295) ---
    { id: "25282", argomento: "Sicurezza a Bordo", testo: "E' sconsigliabile sistemare oggetti sotto il sedile del conducente per evitare che vadano ad intralciare i movimenti dell'autista", immagine: "", rispostaCorretta: true },
    { id: "25283", argomento: "Distrazione", testo: "L'uso del telefono cellulare senza l'ausilio del 'viva-voce' o dell'auricolare è vietato durante la guida", immagine: "", rispostaCorretta: true },
    { id: "25284", argomento: "Sicurezza a Bordo", testo: "Quando si trasportano bambini è consigliabile inserire il dispositivo di sicurezza che impedisce l'apertura delle portiere dall'interno", immagine: "", rispostaCorretta: true },
    { id: "25285", argomento: "Manutenzione", testo: "Il climatizzatore può essere utilmente impiegato anche nel periodo invernale, per sbrinare velocemente il parabrezza", immagine: "", rispostaCorretta: true },
    { id: "25286", argomento: "Distrazione", testo: "Durante la guida è consentito utilizzare il cellulare per comporre sms", immagine: "", rispostaCorretta: false },
    { id: "25287", argomento: "Distrazione", testo: "I sistemi di navigazione satellitare presenti su alcuni veicoli devono essere programmati mentre il veicolo è in movimento", immagine: "", rispostaCorretta: false },
    { id: "25288", argomento: "Segnaletica", testo: "I pannelli a messaggio variabile forniscono indicazioni di pericolo ma non possono avere valore prescrittivo (obbligo o divieto)", immagine: "", rispostaCorretta: false },
    { id: "25289", argomento: "Comportamenti", testo: "Quando la strada è bagnata, se il veicolo che precede sporca il parabrezza, devo sorpassarlo immediatamente", immagine: "", rispostaCorretta: false },
    { id: "25290", argomento: "Visibilità", testo: "Adesivi, ciondoli o altri oggetti applicati sui vetri del veicolo possono ridurre la visibilità del conducente", immagine: "", rispostaCorretta: true },
    { id: "25291", argomento: "Visibilità", testo: "La trasparenza e la pulizia dei vetri dei finestrini del veicolo garantiscono una migliore visibilità esterna", immagine: "", rispostaCorretta: true },
    { id: "25292", argomento: "Visibilità", testo: "Occorre verificare le spazzole del tergicristallo per sostituirle se sono consumate", immagine: "", rispostaCorretta: true },
    { id: "25293", argomento: "Visibilità", testo: "Occorre verificare che nel serbatoio del dispositivo lavacristallo sia sempre presente liquido per detergere i vetri", immagine: "", rispostaCorretta: true },
    { id: "25294", argomento: "Visibilità", testo: "In caso di lesioni o rottura del vetro anteriore del veicolo, bisogna ripararlo con del nastro adesivo trasparente", immagine: "", rispostaCorretta: false },
    { id: "25295", argomento: "Visibilità", testo: "Se il parabrezza è coperto dalla polvere, bisogna utilizzare il dispositivo di disappannamento", immagine: "", rispostaCorretta: false },

    // --- BLOCCO: PNEUMATICI (25296 - 25304) ---
    { id: "25296", argomento: "Pneumatici", testo: "Bisogna utilizzare esclusivamente pneumatici delle dimensioni previste dall'omologazione del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25297", argomento: "Pneumatici", testo: "Per una maggiore sicurezza, sulle ruote dello stesso asse bisogna utilizzare pneumatici uguali", immagine: "", rispostaCorretta: true },
    { id: "25298", argomento: "Pneumatici", testo: "Bisogna controllare le condizioni dei pneumatici anche sui lati, per prevenire improvvisi scoppi o sgonfiamenti", immagine: "", rispostaCorretta: true },
    { id: "25299", argomento: "Pneumatici", testo: "Per garantire l'aderenza, bisogna controllare che la pressione di gonfiaggio sia quella consigliata dalla casa costruttrice", immagine: "", rispostaCorretta: true },
    { id: "25300", argomento: "Pneumatici", testo: "La pressione di gonfiaggio troppo bassa degli pneumatici ne provoca l'anomalo consumo ai bordi", immagine: "", rispostaCorretta: true },
    { id: "25301", argomento: "Pneumatici", testo: "Non bisogna mai invertire la posizione degli pneumatici, per permettere loro di adattarsi meglio", immagine: "", rispostaCorretta: false },
    { id: "25302", argomento: "Pneumatici", testo: "Per garantire l'aderenza, bisogna controllare solo la pressione di gonfiaggio degli pneumatici delle ruote motrici", immagine: "", rispostaCorretta: false },
    { id: "25303", argomento: "Pneumatici", testo: "Per migliorare il raffreddamento degli pneumatici, bisogna diminuire la pressione di gonfiaggio", immagine: "", rispostaCorretta: false },
    { id: "25304", argomento: "Pneumatici", testo: "La pressione di gonfiaggio troppo bassa degli pneumatici ne provoca l'anomalo consumo della parte centrale e dei bordi", immagine: "", rispostaCorretta: false },

    // --- BLOCCO: FRENI (25305 - 25338) ---
    { id: "25305", argomento: "Freni", testo: "Gli impianti di frenatura dei veicoli leggeri sono spesso dotati di servofreno", immagine: "", rispostaCorretta: true },
    { id: "25306", argomento: "Freni", testo: "Negli impianti di frenatura, l'energia cinetica dell'autoveicolo viene trasformata in calore grazie all'attrito", immagine: "", rispostaCorretta: true },
    { id: "25307", argomento: "Freni", testo: "Le parti dell'impianto frenante maggiormente sollecitate dalle alte temperature sono le guarnizioni di attrito", immagine: "", rispostaCorretta: true },
    { id: "25308", argomento: "Freni", testo: "Il freno di stazionamento deve essere utilizzato per bloccare il veicolo in sosta o per situazioni di emergenza", immagine: "", rispostaCorretta: true },
    { id: "25309", argomento: "Freni", testo: "Il livello del liquido idraulico dei freni deve essere periodicamente controllato", immagine: "", rispostaCorretta: true },
    { id: "25310", argomento: "Freni", testo: "Il freno di stazionamento deve essere in grado di tenere bloccato il veicolo in sosta anche su strade in pendenza", immagine: "", rispostaCorretta: true },
    { id: "25311", argomento: "Freni", testo: "Il servofreno a depressione non può funzionare a motore spento", immagine: "", rispostaCorretta: true },
    { id: "25312", argomento: "Freni", testo: "Il freno di stazionamento non deve essere utilizzato per la frenatura di servizio", immagine: "", rispostaCorretta: true },
    { id: "25313", argomento: "Freni", testo: "Il circuito frenante è di tipo sigillato, pertanto non è necessario un periodico controllo del livello del liquido", immagine: "", rispostaCorretta: false },
    { id: "25314", argomento: "Freni", testo: "Il freno di stazionamento deve essere utilizzato per la frenatura di servizio su strade a forte pendenza", immagine: "", rispostaCorretta: false },
    { id: "25315", argomento: "Freni", testo: "Il servofreno a depressione può funzionare anche a motore spento, purché sia inserita la chiave di accensione", immagine: "", rispostaCorretta: false },
    { id: "25316", argomento: "Freni", testo: "In caso di frenata di emergenza, il conducente deve inserire rapidamente la retromarcia", immagine: "", rispostaCorretta: false },
    { id: "25318", argomento: "Freni", testo: "Una frenatura poco efficiente può essere causata dalla presenza d'aria o vapore nel circuito idraulico", immagine: "", rispostaCorretta: true },
    { id: "25319", argomento: "Freni", testo: "Una frenatura poco efficiente può essere causata dal consumo eccessivo delle guarnizioni frenanti", immagine: "", rispostaCorretta: true },
    { id: "25320", argomento: "Freni", testo: "Una frenatura poco efficiente può essere causata dal consumo irregolare dei tamburi o dei dischi", immagine: "", rispostaCorretta: true },
    { id: "25321", argomento: "Freni", testo: "Una frenatura squilibrata può essere causata dalla differente pressione di gonfiaggio dei pneumatici dello stesso asse", immagine: "", rispostaCorretta: true },
    { id: "25322", argomento: "Freni", testo: "Una frenatura poco efficiente può essere causata dall'eccessivo riscaldamento delle guarnizioni frenanti", immagine: "", rispostaCorretta: true },
    { id: "25323", argomento: "Freni", testo: "Una frenatura poco efficiente o squilibrata può essere causata dal carico eccessivo o mal ripartito", immagine: "", rispostaCorretta: true },
    { id: "25324", argomento: "Freni", testo: "Una frenatura poco efficiente può essere causata da eccessive e ripetute frenate", immagine: "", rispostaCorretta: true },
    { id: "25325", argomento: "Freni", testo: "Con freni squilibrati può avvenire che, in frenata, si blocchino soltanto le ruote di un lato", immagine: "", rispostaCorretta: true },
    { id: "25326", argomento: "Freni", testo: "Con freni squilibrati il veicolo può sbandare, dirigendosi verso il lato della ruota che si blocca per prima", immagine: "", rispostaCorretta: true },
    { id: "25327", argomento: "Freni", testo: "Con freni squilibrati si manifesta, in genere, un'usura irregolare e non omogenea dei battistrada", immagine: "", rispostaCorretta: true },
    { id: "25328", argomento: "Freni", testo: "Una frenatura squilibrata può essere causata dal consumo dei meccanismi del freno di stazionamento", immagine: "", rispostaCorretta: false },
    { id: "25329", argomento: "Freni", testo: "Una frenatura squilibrata può essere causata dall'insufficiente lubrificazione dei tamburi o dei dischi", immagine: "", rispostaCorretta: false },
    { id: "25330", argomento: "Freni", testo: "Una frenatura poco efficiente può essere causata dall'eccessivo gioco del pedale della frizione", immagine: "", rispostaCorretta: false },
    { id: "25331", argomento: "Freni", testo: "Una frenatura squilibrata può essere causata dalla presenza del servosterzo su veicoli di piccola cilindrata", immagine: "", rispostaCorretta: false },
    { id: "25332", argomento: "Freni", testo: "Una frenatura squilibrata può essere causata dalla presenza di freni a disco sull'asse posteriore", immagine: "", rispostaCorretta: false },
    { id: "25333", argomento: "Freni", testo: "Una frenatura squilibrata può essere causata da pneumatici invernali montati su tutte e quattro le ruote", immagine: "", rispostaCorretta: false },
    { id: "25334", argomento: "Freni", testo: "Una frenatura squilibrata può essere causata da pneumatici invernali utilizzati su strade non innevate", immagine: "", rispostaCorretta: false },
    { id: "25335", argomento: "Freni", testo: "Una frenatura squilibrata può essere causata dall'utilizzo di veicoli a metano su strade di montagna", immagine: "", rispostaCorretta: false },
    { id: "25336", argomento: "Freni", testo: "Con freni squilibrati si manifesta in genere un surriscaldamento del liquido refrigerante del motore", immagine: "", rispostaCorretta: false },
    { id: "25337", argomento: "Freni", testo: "Su discese molto ripide è bene viaggiare con il freno a mano inserito parzialmente", immagine: "", rispostaCorretta: false },
    { id: "25338", argomento: "Freni", testo: "Il cambio delle pastiglie dei freni è un'operazione che può essere svolta da qualunque conducente", immagine: "", rispostaCorretta: false },

    // --- BLOCCO: SOSPENSIONI E AMMORTIZZATORI (25339 - 25385) ---
    { id: "25339", argomento: "Sospensioni", testo: "Le sospensioni di un veicolo a motore sono poste tra il telaio e le ruote", immagine: "", rispostaCorretta: true },
    { id: "25340", argomento: "Sospensioni", testo: "Le sospensioni di un veicolo a motore servono a garantire un buon confort di marcia", immagine: "", rispostaCorretta: true },
    { id: "25341", argomento: "Sospensioni", testo: "Le sospensioni servono a garantire che le ruote rimangano aderenti al fondo stradale", immagine: "", rispostaCorretta: true },
    { id: "25342", argomento: "Sospensioni", testo: "Le sospensioni servono a smorzare gli urti trasmessi dalle asperità del terreno", immagine: "", rispostaCorretta: true },
    { id: "25343", argomento: "Sospensioni", testo: "Le sospensioni di un veicolo a motore collaborano a rendere più confortevole e sicura la guida", immagine: "", rispostaCorretta: true },
    { id: "25345", argomento: "Sospensioni", testo: "Le sospensioni sono in genere poste sulle ruote anteriori, ma non su quelle posteriori", immagine: "", rispostaCorretta: false },
    { id: "25346", argomento: "Sospensioni", testo: "Le sospensioni servono a irrigidire il veicolo per far percepire tutti i saltellamenti della strada", immagine: "", rispostaCorretta: false },
    { id: "25347", argomento: "Sospensioni", testo: "Le sospensioni di un veicolo a motore non entrano in funzione su strada rettilinea", immagine: "", rispostaCorretta: false },
    { id: "25348", argomento: "Sospensioni", testo: "Le sospensioni possono diventare inefficienti per usura o per aver subito urti troppo forti", immagine: "", rispostaCorretta: true },
    { id: "25349", argomento: "Sospensioni", testo: "Un veicolo con sospensioni inefficienti ha problemi di tenuta di strada", immagine: "", rispostaCorretta: true },
    { id: "25350", argomento: "Sospensioni", testo: "Il sovraccarico del veicolo può comportare la rottura delle sospensioni", immagine: "", rispostaCorretta: true },
    { id: "25351", argomento: "Sospensioni", testo: "Il sovraccarico del veicolo può comportare la temporanea inefficienza delle sospensioni", immagine: "", rispostaCorretta: true },
    { id: "25352", argomento: "Sospensioni", testo: "Il sovraccarico ripetuto del veicolo può comportare la rapida usura delle sospensioni", immagine: "", rispostaCorretta: true },
    { id: "25353", argomento: "Sospensioni", testo: "Un veicolo con sospensioni inefficienti riduce il confort di marcia", immagine: "", rispostaCorretta: true },
    { id: "25354", argomento: "Sospensioni", testo: "Un veicolo con sospensioni inefficienti aumenta l'affaticamento alla guida del conducente", immagine: "", rispostaCorretta: true },
    { id: "25355", argomento: "Sospensioni", testo: "Un veicolo con sospensioni inefficienti può causare l'anomalo orientamento degli anabbaglianti", immagine: "", rispostaCorretta: true },
    { id: "25356", argomento: "Sospensioni", testo: "Il sovraccarico del veicolo non comporta problemi per le sospensioni", immagine: "", rispostaCorretta: false },
    { id: "25357", argomento: "Sospensioni", testo: "Se il veicolo è sovraccarico, basta aumentare la pressione dei pneumatici di un bar per le sospensioni", immagine: "", rispostaCorretta: false },
    { id: "25358", argomento: "Sospensioni", testo: "Le sospensioni del veicolo devono essere sostituite all'incirca ogni trentamila chilometri", immagine: "", rispostaCorretta: false },
    { id: "25359", argomento: "Sospensioni", testo: "Il sovraccarico comporta difficoltà di guida, ma non comporta problemi per le sospensioni", immagine: "", rispostaCorretta: false },
    { id: "25360", argomento: "Sospensioni", testo: "Le sospensioni, essendo di materiali elastici, non subiscono danni per gli urti durante la marcia", immagine: "", rispostaCorretta: false },
    { id: "25361", argomento: "Sospensioni", testo: "Le sospensioni sono realizzate per non necessitare di verifiche per tutta la durata della garanzia", immagine: "", rispostaCorretta: false },
    { id: "25362", argomento: "Sospensioni", testo: "Le sospensioni non collaborano alla dirigibilità del veicolo", immagine: "", rispostaCorretta: false },
    { id: "25363", argomento: "Sospensioni", testo: "La rottura di una sola delle quattro sospensioni non comporta problemi per la guida", immagine: "", rispostaCorretta: false },
    { id: "25364", argomento: "Sospensioni", testo: "Gli ammortizzatori di un veicolo a motore servono a ridurre le oscillazioni delle sospensioni", immagine: "", rispostaCorretta: true },
    { id: "25365", argomento: "Sospensioni", testo: "Gli ammortizzatori collaborano alla tenuta di strada del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25366", argomento: "Sospensioni", testo: "Gli ammortizzatori servono, tra l'altro, a garantire la tenuta di strada del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25367", argomento: "Sospensioni", testo: "Il sovraccarico del veicolo può rendere inefficienti gli ammortizzatori", immagine: "", rispostaCorretta: true },
    { id: "25368", argomento: "Sospensioni", testo: "Il sovraccarico del veicolo può comportare un'usura precoce degli ammortizzatori", immagine: "", rispostaCorretta: true },
    { id: "25369", argomento: "Sospensioni", testo: "Gli ammortizzatori non necessitano di verifiche fino a quando dura la garanzia del veicolo", immagine: "", rispostaCorretta: false },
    { id: "25370", argomento: "Sospensioni", testo: "Il sovraccarico non causa problemi agli ammortizzatori se il conducente guida con prudenza", immagine: "", rispostaCorretta: false },
    { id: "25371", argomento: "Sospensioni", testo: "Se il veicolo è sovraccarico, basta aumentare la pressione dei pneumatici di mezzo bar", immagine: "", rispostaCorretta: false },
    { id: "25372", argomento: "Sospensioni", testo: "Il conducente può in ogni caso regolare la rigidità degli ammortizzatori", immagine: "", rispostaCorretta: false },
    { id: "25373", argomento: "Sospensioni", testo: "La rigidità degli ammortizzatori può essere controllata dal proprietario senza andare in officina", immagine: "", rispostaCorretta: false },
    { id: "25374", argomento: "Sospensioni", testo: "Gli ammortizzatori scarichi provocano un comportamento anomalo del veicolo in frenata", immagine: "", rispostaCorretta: true },
    { id: "25375", argomento: "Sospensioni", testo: "Gli ammortizzatori scarichi provocano un comportamento anomalo del veicolo, in curva", immagine: "", rispostaCorretta: true },
    { id: "25376", argomento: "Sospensioni", testo: "Gli ammortizzatori scarichi provocano l'usura non uniforme del battistrada dei pneumatici", immagine: "", rispostaCorretta: true },
    { id: "25377", argomento: "Sospensioni", testo: "In un veicolo a motore, gli ammortizzatori scarichi aumentano il rischio di rottura delle molle", immagine: "", rispostaCorretta: true },
    { id: "25378", argomento: "Sospensioni", testo: "In un veicolo a motore, gli ammortizzatori scarichi provocano una diminuzione del comfort", immagine: "", rispostaCorretta: true },
    { id: "25379", argomento: "Sospensioni", testo: "In un veicolo a motore, gli ammortizzatori scarichi peggiorano la tenuta di strada", immagine: "", rispostaCorretta: true },
    { id: "25380", argomento: "Sospensioni", testo: "In un veicolo, gli ammortizzatori scarichi provocano un anomalo funzionamento del motore", immagine: "", rispostaCorretta: false },
    { id: "25381", argomento: "Sospensioni", testo: "In un veicolo a motore, gli ammortizzatori scarichi provocano un maggior consumo di lubrificante", immagine: "", rispostaCorretta: false },
    { id: "25382", argomento: "Sospensioni", testo: "Gli ammortizzatori scarichi migliorano la tenuta di strada abbassando il telaio", immagine: "", rispostaCorretta: false },
    { id: "25383", argomento: "Sospensioni", testo: "Gli ammortizzatori possono essere sostituiti con una sospensione rinforzata", immagine: "", rispostaCorretta: false },
    { id: "25384", argomento: "Sospensioni", testo: "Un veicolo a motore è dotato di sospensioni oppure di ammortizzatori, ma non di tutti e due", immagine: "", rispostaCorretta: false },
    { id: "25385", argomento: "Sospensioni", testo: "Gli ammortizzatori, se del tipo a circuito sigillato, non necessitano di manutenzione", immagine: "", rispostaCorretta: false },
    // --- BLOCCO: STABILITÀ E RIBALTAMENTO (25208 - 25216) ---
    { id: "25208", argomento: "Stabilità", testo: "Il ribaltamento in curva del veicolo è favorito da un carico posto in alto", immagine: "", rispostaCorretta: true },
    { id: "25209", argomento: "Stabilità", testo: "Il ribaltamento in curva del veicolo è favorito dal carico non stabilmente fissato", immagine: "", rispostaCorretta: true },
    { id: "25210", argomento: "Stabilità", testo: "Il ribaltamento in curva del veicolo è favorito da una ridotta distanza fra ruote dello stesso asse (carreggiata stretta)", immagine: "", rispostaCorretta: true },
    { id: "25211", argomento: "Stabilità", testo: "Il ribaltamento in curva del veicolo è favorito da un raggio di curvatura della strada piccolo (curva stretta)", immagine: "", rispostaCorretta: true },
    { id: "25212", argomento: "Stabilità", testo: "Il ribaltamento in curva del veicolo è favorito da una ampia distanza fra ruote dello stesso asse (carreggiata larga)", immagine: "", rispostaCorretta: false },
    { id: "25213", argomento: "Stabilità", testo: "Il ribaltamento in curva del veicolo è favorito da un carico posto in basso", immagine: "", rispostaCorretta: false },
    { id: "25214", argomento: "Stabilità", testo: "Il ribaltamento in curva del veicolo è favorito da un raggio di curvatura della strada ampio (curva larga)", immagine: "", rispostaCorretta: false },
    { id: "25215", argomento: "Stabilità", testo: "La forza ribaltante in curva aumenta all'aumentare della velocità", immagine: "", rispostaCorretta: true },
    { id: "25216", argomento: "Stabilità", testo: "La forza ribaltante in curva diminuisce all'aumentare della velocità", immagine: "", rispostaCorretta: false },

    // --- BLOCCO: SISTEMA ABS (25217 - 25228 & 25267 - 25272) ---
    { id: "25217", argomento: "Freni", testo: "L'A.B.S. impedisce alle ruote di bloccarsi", immagine: "", rispostaCorretta: true },
    { id: "25218", argomento: "Freni", testo: "L'A.B.S. consente di correggere la traiettoria del veicolo anche durante una frenata di emergenza", immagine: "", rispostaCorretta: true },
    { id: "25219", argomento: "Freni", testo: "L'A.B.S. consente di utilizzare la massima forza aderente, in frenata", immagine: "", rispostaCorretta: true },
    { id: "25220", argomento: "Freni", testo: "L'A.B.S. è in grado di agire su tutte le ruote, intervenendo di volta in volta su quelle che stanno per bloccarsi", immagine: "", rispostaCorretta: true },
    { id: "25221", argomento: "Freni", testo: "L'A.B.S. agisce anche quando gli pneumatici sono usurati", immagine: "", rispostaCorretta: true },
    { id: "25222", argomento: "Freni", testo: "L'A.B.S. agisce anche quando l'asfalto è bagnato", immagine: "", rispostaCorretta: true },
    { id: "25223", argomento: "Freni", testo: "L'A.B.S. rende la frenata più sicura perché impedisce alle ruote di bloccarsi", immagine: "", rispostaCorretta: true },
    { id: "25224", argomento: "Freni", testo: "L'A.B.S. favorisce il bloccaggio delle ruote", immagine: "", rispostaCorretta: false },
    { id: "25225", argomento: "Freni", testo: "L'A.B.S. impedisce, durante la frenata, di modificare la traiettoria del veicolo", immagine: "", rispostaCorretta: false },
    { id: "25226", argomento: "Freni", testo: "L'A.B.S. impedisce di utilizzare la massima forza aderente, in frenata", immagine: "", rispostaCorretta: false },
    { id: "25227", argomento: "Freni", testo: "L'A.B.S. non agisce sulle ruote motrici", immagine: "", rispostaCorretta: false },
    { id: "25228", argomento: "Freni", testo: "L'A.B.S. non si attiva se gli pneumatici sono usurati", immagine: "", rispostaCorretta: false },
    { id: "25267", argomento: "Freni", testo: "In caso di frenata di emergenza, con entrata in azione dell'ABS, bisogna continuare a premere con forza il pedale", immagine: "", rispostaCorretta: true },
    { id: "25272", argomento: "Freni", testo: "In caso di frenata di emergenza, con entrata in azione dell'ABS, bisogna immediatamente diminuire la pressione sul pedale", immagine: "", rispostaCorretta: false },

    // --- BLOCCO: MANUTENZIONE PNEUMATICI (25229 - 25255) ---
    { id: "25229", argomento: "Pneumatici", testo: "Si deve controllare periodicamente la pressione di gonfiaggio dei pneumatici, compresa quella della ruota di scorta", immagine: "", rispostaCorretta: true },
    { id: "25230", argomento: "Pneumatici", testo: "La pressione di gonfiaggio degli pneumatici va adeguata alle condizioni di peso del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25231", argomento: "Pneumatici", testo: "La corretta pressione di gonfiaggio dipende dal carico del veicolo e dal numero dei passeggeri", immagine: "", rispostaCorretta: true },
    { id: "25232", argomento: "Pneumatici", testo: "Un'insufficiente pressione di gonfiaggio degli pneumatici fa aumentare l'attrito e anche i consumi di carburante", immagine: "", rispostaCorretta: true },
    { id: "25233", argomento: "Pneumatici", testo: "La pressione di gonfiaggio dei pneumatici deve essere controllata quando la gomma è fredda", immagine: "", rispostaCorretta: true },
    { id: "25234", argomento: "Pneumatici", testo: "Il sistema automatico di rilevamento della pressione fa aumentare la sicurezza dei veicoli che ne sono dotati", immagine: "", rispostaCorretta: true },
    { id: "25235", argomento: "Pneumatici", testo: "Se si misura la pressione quando la gomma è calda, si ha una corretta lettura dei valori", immagine: "", rispostaCorretta: false },
    { id: "25236", argomento: "Pneumatici", testo: "La pressione di gonfiaggio va controllata dopo aver percorso alcuni chilometri, appena la gomma si è surriscaldata", immagine: "", rispostaCorretta: false },
    { id: "25237", argomento: "Pneumatici", testo: "La pressione di gonfiaggio va stabilita in base al materiale con cui sono realizzati i cerchioni", immagine: "", rispostaCorretta: false },
    { id: "25238", argomento: "Pneumatici", testo: "Prima di iniziare un lungo viaggio, è opportuno aumentare la pressione di gonfiaggio degli pneumatici", immagine: "", rispostaCorretta: false },
    { id: "25239", argomento: "Pneumatici", testo: "Nei veicoli con rimorchio, la pressione del veicolo trainante deve essere uguale a quella del rimorchio", immagine: "", rispostaCorretta: false },
    { id: "25240", argomento: "Pneumatici", testo: "Lo spessore minimo del battistrada degli pneumatici di un autoveicolo deve essere di 1,6 millimetri", immagine: "", rispostaCorretta: true },
    { id: "25241", argomento: "Pneumatici", testo: "E' consigliabile sostituire gli pneumatici dopo alcuni anni, anche se non sono consumati", immagine: "", rispostaCorretta: true },
    { id: "25242", argomento: "Pneumatici", testo: "Lo spessore minimo del battistrada degli pneumatici di un motociclo deve essere di 1,0 millimetri", immagine: "", rispostaCorretta: true },
    { id: "25243", argomento: "Pneumatici", testo: "Se in uno pneumatico tubeless si è conficcato un chiodo, è possibile continuare con cautela fino a riparazione", immagine: "", rispostaCorretta: true },
    { id: "25244", argomento: "Pneumatici", testo: "Gli pneumatici tubeless possono essere riparati solo con apposite bombolette contenenti mastice", immagine: "", rispostaCorretta: false },
    { id: "25245", argomento: "Pneumatici", testo: "Gli pneumatici tubeless, in caso di foratura, si sgonfiano lentamente", immagine: "", rispostaCorretta: true },
    { id: "25246", argomento: "Pneumatici", testo: "Gli pneumatici con camera d'aria, in caso di foratura, si sgonfiano lentamente", immagine: "", rispostaCorretta: false },
    { id: "25247", argomento: "Pneumatici", testo: "Se in uno pneumatico tubeless si è conficcato un chiodo, bisogna estrarlo subito per evitare esplosioni", immagine: "", rispostaCorretta: false },
    { id: "25248", argomento: "Pneumatici", testo: "Gli pneumatici gonfiati con l'azoto devono essere tenuti a minore pressione rispetto a quelli con aria", immagine: "", rispostaCorretta: false },
    { id: "25249", argomento: "Pneumatici", testo: "Gli pneumatici chiodati possono essere usati limitatamente ad un predeterminato periodo dell'anno", immagine: "", rispostaCorretta: true },
    { id: "25250", argomento: "Pneumatici", testo: "E' consigliabile che gli pneumatici invernali vengano montati su tutte le ruote", immagine: "", rispostaCorretta: true },
    { id: "25251", argomento: "Pneumatici", testo: "Chi fa uso di catene da neve non omologate è sanzionabile come se ne fosse sprovvisto", immagine: "", rispostaCorretta: true },
    { id: "25252", argomento: "Pneumatici", testo: "Gli pneumatici chiodati vanno montati solo su due ruote dello stesso asse", immagine: "", rispostaCorretta: false },
    { id: "25253", argomento: "Pneumatici", testo: "Nei veicoli 4x4, le catene da neve devono essere montate sulle ruote posteriori", immagine: "", rispostaCorretta: false },
    { id: "25254", argomento: "Pneumatici", testo: "Gli organi della sospensione non si danneggiano se nei tratti senza neve si fa uso di catene", immagine: "", rispostaCorretta: false },
    { id: "25255", argomento: "Pneumatici", testo: "I veicoli muniti di pneumatici invernali devono rispettare limiti di velocità massima inferiori a quelli ordinari", immagine: "", rispostaCorretta: false },

    // --- BLOCCO: SOSTITUZIONE RUOTA (25256 - 25266) ---
    { id: "25256", argomento: "Manutenzione", testo: "Per la sostituzione di una ruota conviene stazionare il veicolo su un terreno orizzontale e stabile", immagine: "", rispostaCorretta: true },
    { id: "25257", argomento: "Manutenzione", testo: "Prima di sostituire una ruota, bisogna azionare il freno di stazionamento e inserire la prima marcia o retromarcia", immagine: "", rispostaCorretta: true },
    { id: "25258", argomento: "Manutenzione", testo: "Prima di sollevare il veicolo per sostituire una ruota, è conveniente allentare leggermente i bulloni", immagine: "", rispostaCorretta: true },
    { id: "25259", argomento: "Manutenzione", testo: "Durante la sostituzione di una ruota tramite il cric, bisogna evitare di mettersi sotto il veicolo", immagine: "", rispostaCorretta: true },
    { id: "25260", argomento: "Manutenzione", testo: "Sostituendo una ruota, bisogna stringere leggermente i bulloni a veicolo sollevato e bloccarli dopo averlo abbassato", immagine: "", rispostaCorretta: true },
    { id: "25261", argomento: "Manutenzione", testo: "In caso di foratura, è opportuno far scendere i passeggeri e farli sistemare fuori dalla carreggiata", immagine: "", rispostaCorretta: true },
    { id: "25262", argomento: "Manutenzione", testo: "Per smontare una ruota bisogna togliere i bulloni prima di sollevare il veicolo con il cric", immagine: "", rispostaCorretta: false },
    { id: "25263", argomento: "Manutenzione", testo: "Per smontare una ruota bisogna fissare il cric in un punto qualsiasi del longherone del veicolo", immagine: "", rispostaCorretta: false },
    { id: "25264", argomento: "Manutenzione", testo: "Per smontare una ruota bisogna fissare il cric il più lontano possibile dalla ruota da sostituire", immagine: "", rispostaCorretta: false },
    { id: "25265", argomento: "Manutenzione", testo: "L'applicazione del ruotino consente di raggiungere la velocità di 120 km/h", immagine: "", rispostaCorretta: false },
    { id: "25266", argomento: "Manutenzione", testo: "Nei veicoli con il ruotino applicato non è consentito trasportare passeggeri", immagine: "", rispostaCorretta: false },

    // --- BLOCCO: USO DEI FRENI E CAMBIO (25268 - 25275) ---
    { id: "25268", argomento: "Freni", testo: "L'azione frenante esercitata dal motore è massima se si inserisce la prima marcia", immagine: "", rispostaCorretta: true },
    { id: "25269", argomento: "Freni", testo: "L'uso prolungato e ripetuto dei freni ne comporta la diminuzione dell'efficienza per surriscaldamento", immagine: "", rispostaCorretta: true },
    { id: "25270", argomento: "Freni", testo: "Percorrendo lunghe e ripide discese è necessario inserire una marcia bassa per evitare di surriscaldare i freni", immagine: "", rispostaCorretta: true },
    { id: "25271", argomento: "Freni", testo: "Dopo il lavaggio del veicolo, è opportuno eseguire una prova di frenata", immagine: "", rispostaCorretta: true },
    { id: "25273", argomento: "Freni", testo: "Tutti i veicoli sono dotati del freno di stazionamento che si aziona con comando manuale", immagine: "", rispostaCorretta: false },
    { id: "25274", argomento: "Freni", testo: "Il freno di stazionamento si utilizza durante la marcia, per frenare o arrestare il veicolo", immagine: "", rispostaCorretta: false },
    { id: "25275", argomento: "Freni", testo: "Percorrendo lunghe e ripide discese è opportuno marciare con il cambio in folle per risparmiare carburante", immagine: "", rispostaCorretta: false },

    // --- BLOCCO: EMERGENZA INCENDIO (25276 - 25281) ---
    { id: "25276", argomento: "Emergenza", testo: "Dopo un incidente, se c'è rischio d'incendio è opportuno spegnere il quadro elettrico girando la chiave", immagine: "", rispostaCorretta: true },
    { id: "25277", argomento: "Emergenza", testo: "In caso di principio d'incendio, in mancanza di estintore, si può gettare sabbia o terra alla base delle fiamme", immagine: "", rispostaCorretta: true },
    { id: "25278", argomento: "Emergenza", testo: "In caso di principio d'incendio, in mancanza di estintore si può utilizzare una coperta bagnata per spegnere le fiamme", immagine: "", rispostaCorretta: true },
    { id: "25279", argomento: "Emergenza", testo: "Dopo un incidente, se c'è un principio d'incendio occorre svuotarne immediatamente il serbatoio", immagine: "", rispostaCorretta: false },
    { id: "25280", argomento: "Emergenza", testo: "Dopo un incidente, il rischio d'incendio è maggiore se il veicolo ha l'interruttore inerziale", immagine: "", rispostaCorretta: false },
    { id: "25281", argomento: "Emergenza", testo: "Se c'è un principio d'incendio in un veicolo a GPL, occorre smontare subito il serbatoio del carburante", immagine: "", rispostaCorretta: false },
    // --- BLOCCO: INQUINAMENTO E CONSUMI (25108 - 25151) ---
    { id: "25108", argomento: "Inquinamento", testo: "L'inquinamento dell'aria prodotto dai veicoli può dipendere da un funzionamento irregolare del motore", immagine: "", rispostaCorretta: true },
    { id: "25109", argomento: "Inquinamento", testo: "L'inquinamento dell'aria può essere ridotto, controllando che il veicolo sia sempre nelle condizioni ottimali", immagine: "", rispostaCorretta: true },
    { id: "25110", argomento: "Inquinamento", testo: "Adottando uno stile di guida che limiti i consumi di carburante, è possibile ridurre l'inquinamento dell'aria", immagine: "", rispostaCorretta: true },
    { id: "25111", argomento: "Inquinamento", testo: "L'inquinamento atmosferico può essere ridotto, controllando che il filtro dell'aria non sia sporco o intasato", immagine: "", rispostaCorretta: true },
    { id: "25112", argomento: "Inquinamento", testo: "L'inquinamento atmosferico scompare del tutto accelerando a fondo per l'alta temperatura", immagine: "", rispostaCorretta: false },
    { id: "25113", argomento: "Inquinamento", testo: "L'inquinamento dell'aria prodotto dai veicoli diminuisce se si lascia acceso il climatizzatore", immagine: "", rispostaCorretta: false },
    { id: "25114", argomento: "Inquinamento", testo: "L'inquinamento atmosferico è nullo nei veicoli che rispettano la normativa 'Euro 0'", immagine: "", rispostaCorretta: false },
    { id: "25115", argomento: "Inquinamento", testo: "L'inquinamento dell'aria prodotto dai veicoli aumenta se gli iniettori sono difettosi", immagine: "", rispostaCorretta: true },
    { id: "25116", argomento: "Inquinamento", testo: "Una maggiore emissione di fumo dallo scarico è sintomo di maggior inquinamento causato dal motore", immagine: "", rispostaCorretta: true },
    { id: "25117", argomento: "Inquinamento", testo: "L'inquinamento dell'aria prodotto dai veicoli è maggiore se il fumo di scarico presenta colore scuro", immagine: "", rispostaCorretta: true },
    { id: "25118", argomento: "Inquinamento", testo: "L'inquinamento dell'aria prodotto dai veicoli può causare danni alle vie respiratorie e irritazione agli occhi", immagine: "", rispostaCorretta: true },
    { id: "25119", argomento: "Inquinamento", testo: "L'inquinamento dell'aria prodotto dai veicoli fa aumentare lo smog, le piogge acide e l'effetto serra", immagine: "", rispostaCorretta: true },
    { id: "25120", argomento: "Inquinamento", testo: "L'inquinamento dell'aria è dovuto per la maggior parte ai gas di scarico della combustione interna", immagine: "", rispostaCorretta: true },
    { id: "25121", argomento: "Inquinamento", testo: "L'inquinamento atmosferico prodotto dai veicoli dipende principalmente dall'umidità presente nell'aria", immagine: "", rispostaCorretta: false },
    { id: "25122", argomento: "Inquinamento", testo: "L'inquinamento dell'aria prodotto dai veicoli a motore può diminuire se si alleggerisce il peso del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25123", argomento: "Inquinamento", testo: "L'inquinamento dell'aria può essere ridotto scegliendo veicoli elettrici, a metano o GPL", immagine: "", rispostaCorretta: true },
    { id: "25124", argomento: "Inquinamento", testo: "L'inquinamento dell'aria può diminuire se si spegne il motore in caso di arresto prolungato", immagine: "", rispostaCorretta: true },
    { id: "25125", argomento: "Inquinamento", testo: "L'inquinamento dell'aria può essere ridotto evitando di usare il veicolo per brevi percorsi", immagine: "", rispostaCorretta: true },
    { id: "25126", argomento: "Inquinamento", testo: "Chi emette troppi gas inquinanti può subire una sanzione e il ritiro della carta di circolazione", immagine: "", rispostaCorretta: true },
    { id: "25127", argomento: "Inquinamento", testo: "L'inquinamento dell'aria può diminuire se si sistemano i bagagli sul tetto dell'autovettura", immagine: "", rispostaCorretta: false },
    { id: "25128", argomento: "Inquinamento", testo: "L'inquinamento dell'aria può diminuire se si circola sempre con marce basse", immagine: "", rispostaCorretta: false },
    { id: "25129", argomento: "Inquinamento", testo: "L'inquinamento dell'aria può diminuire se si accelera tenendo premuto il pedale della frizione", immagine: "", rispostaCorretta: false },
    { id: "25130", argomento: "Inquinamento", testo: "L'inquinamento dell'aria può diminuire se si accelera con il cambio in folle", immagine: "", rispostaCorretta: false },
    { id: "25131", argomento: "Inquinamento", testo: "Per diminuire l'inquinamento atmosferico bisogna far sostituire periodicamente il filtro dell'aria", immagine: "", rispostaCorretta: true },
    { id: "25132", argomento: "Inquinamento", testo: "Nei motori diesel, bisogna far controllare periodicamente pompa di iniezione ed iniettori per ridurre l'inquinamento", immagine: "", rispostaCorretta: true },
    { id: "25133", argomento: "Inquinamento", testo: "Bisogna far controllare il motore se il fumo dello scarico risulta troppo scuro per ridurre l'inquinamento", immagine: "", rispostaCorretta: true },
    { id: "25134", argomento: "Inquinamento", testo: "Per diminuire l'inquinamento dell'aria non bisogna accelerare e frenare spesso durante la marcia", immagine: "", rispostaCorretta: true },
    { id: "25135", argomento: "Inquinamento", testo: "Bisogna dare un breve colpo di acceleratore prima di cambiare marcia per diminuire l'inquinamento", immagine: "", rispostaCorretta: false },
    { id: "25136", argomento: "Inquinamento", testo: "Per diminuire l'inquinamento atmosferico bisogna utilizzare il motore al massimo numero di giri", immagine: "", rispostaCorretta: false },
    { id: "25137", argomento: "Inquinamento", testo: "Bisogna sostituire periodicamente il filtro antipolline per diminuire l'inquinamento dei gas di scarico", immagine: "", rispostaCorretta: false },
    { id: "25138", argomento: "Inquinamento", testo: "Per diminuire l'inquinamento dell'aria bisogna sostituire il filtro dell'olio ad ogni cambio di stagione", immagine: "", rispostaCorretta: false },
    { id: "25139", argomento: "Inquinamento", testo: "Per risparmiare carburante è consigliabile azionare il climatizzatore il meno possibile", immagine: "", rispostaCorretta: true },
    { id: "25140", argomento: "Inquinamento", testo: "Bisogna premere più volte l'acceleratore quando il veicolo è freddo per salvaguardare l'ambiente", immagine: "", rispostaCorretta: false },
    { id: "25141", argomento: "Inquinamento", testo: "Bisogna premere a fondo l'acceleratore per far raggiungere in fretta la temperatura di esercizio", immagine: "", rispostaCorretta: false },
    { id: "25142", argomento: "Inquinamento", testo: "Quando si cambia marcia bisogna premere a fondo il pedale dell'acceleratore per ridurre l'inquinamento", immagine: "", rispostaCorretta: false },
    { id: "25143", argomento: "Inquinamento", testo: "Conviene chiudere i finestrini a velocità medio alte per limitare i consumi di carburante", immagine: "", rispostaCorretta: true },
    { id: "25144", argomento: "Inquinamento", testo: "Per limitare i consumi non conviene usare il portapacchi, ma sistemare i bagagli all'interno", immagine: "", rispostaCorretta: true },
    { id: "25145", argomento: "Inquinamento", testo: "Viaggiare con uno spesso strato di neve sul tetto comporta un aumento dei consumi di carburante", immagine: "", rispostaCorretta: true },
    { id: "25146", argomento: "Inquinamento", testo: "Viaggiare a forte velocità con il tettuccio aperto comporta un aumento dei consumi di carburante", immagine: "", rispostaCorretta: true },
    { id: "25147", argomento: "Inquinamento", testo: "In arresto prolungato in galleria è dannoso azionare il ricircolo dell'aria", immagine: "", rispostaCorretta: false },
    { id: "25148", argomento: "Inquinamento", testo: "I veicoli 'Euro 4' inquinano più di quelli 'Euro 0'", immagine: "", rispostaCorretta: false },
    { id: "25149", argomento: "Inquinamento", testo: "Trainare un rimorchio non comporta un aumento dei consumi di carburante", immagine: "", rispostaCorretta: false },
    { id: "25150", argomento: "Inquinamento", testo: "Chi modifica il motore e la marmitta può incorrere in pesanti sanzioni amministrative", immagine: "", rispostaCorretta: true },
    { id: "25151", argomento: "Inquinamento", testo: "E' consentito modificare liberamente il motore e la marmitta per diminuire l'inquinamento", immagine: "", rispostaCorretta: false },

    // --- BLOCCO: SMALTIMENTO RIFIUTI E REGOLE STRADALI (25152 - 25167) ---
    { id: "25152", argomento: "Rispetto Ambiente", testo: "E' vietato scaricare nella fognatura il liquido antigelo del circuito di raffreddamento", immagine: "", rispostaCorretta: true },
    { id: "25153", argomento: "Rispetto Ambiente", testo: "L'abbandono di una batteria per auto può arrecare gravi danni all'ambiente e alle falde acquifere", immagine: "", rispostaCorretta: true },
    { id: "25154", argomento: "Rispetto Ambiente", testo: "Se si acquista una batteria nuova si può consegnare quella esausta al rivenditore gratuitamente", immagine: "", rispostaCorretta: true },
    { id: "25155", argomento: "Rispetto Ambiente", testo: "Il proprietario che intende rottamare un veicolo deve consegnarlo a un autodemolitore autorizzato", immagine: "", rispostaCorretta: true },
    { id: "25156", argomento: "Rispetto Ambiente", testo: "Nello smaltimento dell'olio motore, bisogna evitare il contatto prolungato con la pelle", immagine: "", rispostaCorretta: true },
    { id: "25157", argomento: "Rispetto Ambiente", testo: "Lo scarico dei residui organici delle autocaravan deve avvenire negli appositi impianti igienico-sanitari", immagine: "", rispostaCorretta: true },
    { id: "25158", argomento: "Rispetto Ambiente", testo: "L'abbandono sul terreno di rifiuti pericolosi (olii, liquidi) non viene sanzionato", immagine: "", rispostaCorretta: false },
    { id: "25159", argomento: "Rispetto Ambiente", testo: "Per rottamare un veicolo, lo si deve consegnare esclusivamente al concessionario della casa costruttrice", immagine: "", rispostaCorretta: false },
    { id: "25160", argomento: "Comportamenti", testo: "E' vietato danneggiare le opere e gli impianti stradali", immagine: "", rispostaCorretta: true },
    { id: "25161", argomento: "Comportamenti", testo: "E' vietato gettare oggetti e rifiuti dai veicoli in movimento", immagine: "", rispostaCorretta: true },
    { id: "25162", argomento: "Comportamenti", testo: "E' vietato sporcare la carreggiata depositando rifiuti", immagine: "", rispostaCorretta: true },
    { id: "25163", argomento: "Comportamenti", testo: "E' vietato immettersi sulle strade con le ruote del veicolo sporche di fango", immagine: "", rispostaCorretta: true },
    { id: "25164", argomento: "Comportamenti", testo: "Su tutte le strade è vietato esercitarsi alla guida", immagine: "", rispostaCorretta: false },
    { id: "25165", argomento: "Comportamenti", testo: "Su tutte le strade sono vietati gli avvisatori acustici (clacson, trombe)", immagine: "", rispostaCorretta: false },
    { id: "25166", argomento: "Comportamenti", testo: "Su tutte le strade è vietato il transito dei veicoli che superano 10 m di lunghezza", immagine: "", rispostaCorretta: false },
    { id: "25167", argomento: "Comportamenti", testo: "E' vietato parcheggiare nelle zone residenziali", immagine: "", rispostaCorretta: false },

    // --- BLOCCO: ADERENZA E FORZE FISICHE (25168 - 25207) ---
    { id: "25168", argomento: "Aderenza", testo: "La forza aderente consente il movimento del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25169", argomento: "Aderenza", testo: "La forza aderente si oppone allo slittamento verso l'esterno della curva", immagine: "", rispostaCorretta: true },
    { id: "25170", argomento: "Aderenza", testo: "La forza aderente consente al veicolo di percorrere la traiettoria voluta", immagine: "", rispostaCorretta: true },
    { id: "25171", argomento: "Aderenza", testo: "La forza aderente si oppone allo slittamento dello pneumatico sull'asfalto", immagine: "", rispostaCorretta: true },
    { id: "25172", argomento: "Aderenza", testo: "La forza aderente non si oppone allo slittamento causato dal vento laterale", immagine: "", rispostaCorretta: false },
    { id: "25173", argomento: "Aderenza", testo: "La forza aderente, se eccessiva, comporta il surriscaldamento dei freni", immagine: "", rispostaCorretta: false },
    { id: "25174", argomento: "Aderenza", testo: "La forza aderente aumenta se l'asfalto è rugoso", immagine: "", rispostaCorretta: true },
    { id: "25175", argomento: "Aderenza", testo: "La forza aderente diminuisce se l'asfalto è bagnato", immagine: "", rispostaCorretta: true },
    { id: "25176", argomento: "Aderenza", testo: "La forza aderente aumenta se l'asfalto è bagnato", immagine: "", rispostaCorretta: false },
    { id: "25177", argomento: "Aderenza", testo: "La forza aderente aumenta se l'asfalto è coperto di foglie", immagine: "", rispostaCorretta: false },
    { id: "25178", argomento: "Aderenza", testo: "La forza aderente aumenta se l'asfalto è coperto di ghiaccio", immagine: "", rispostaCorretta: false },
    { id: "25179", argomento: "Aderenza", testo: "La forza aderente aumenta se l'asfalto è coperto dal fango", immagine: "", rispostaCorretta: false },
    { id: "25180", argomento: "Aderenza", testo: "Se il coefficiente di aderenza diminuisce le ruote motrici potrebbero pattinare", immagine: "", rispostaCorretta: true },
    { id: "25181", argomento: "Aderenza", testo: "Se il coefficiente di aderenza diminuisce lo spazio di frenatura aumenta", immagine: "", rispostaCorretta: true },
    { id: "25182", argomento: "Aderenza", testo: "Se il coefficiente di aderenza è basso bisogna ridurre la velocità", immagine: "", rispostaCorretta: true },
    { id: "25183", argomento: "Aderenza", testo: "Se il coefficiente di aderenza diminuisce lo spazio di frenatura si riduce", immagine: "", rispostaCorretta: false },
    { id: "25184", argomento: "Aderenza", testo: "Se il coefficiente di aderenza è basso bisogna ridurre la velocità solo in curva", immagine: "", rispostaCorretta: false },
    { id: "25185", argomento: "Aderenza", testo: "Il coefficiente di aderenza basso limita la velocità di percorrenza sicura in curva", immagine: "", rispostaCorretta: true },
    { id: "25186", argomento: "Aderenza", testo: "Il coefficiente di aderenza basso favorisce lo slittamento in curva", immagine: "", rispostaCorretta: true },
    { id: "25187", argomento: "Aderenza", testo: "Il coefficiente di aderenza basso aumenta lo spazio di frenatura", immagine: "", rispostaCorretta: true },
    { id: "25188", argomento: "Aderenza", testo: "Il coefficiente di aderenza basso rende pericolose le frenate brusche", immagine: "", rispostaCorretta: true },
    { id: "25189", argomento: "Aderenza", testo: "Il coefficiente di aderenza basso non condiziona la velocità del veicolo", immagine: "", rispostaCorretta: false },
    { id: "25190", argomento: "Aderenza", testo: "Il coefficiente di aderenza basso riduce lo spazio di frenatura", immagine: "", rispostaCorretta: false },
    { id: "25191", argomento: "Aderenza", testo: "Il coefficiente di aderenza basso diminuisce i consumi di carburante", immagine: "", rispostaCorretta: false },
    { id: "25192", argomento: "Aderenza", testo: "Il coefficiente di aderenza basso riduce lo slittamento in curva", immagine: "", rispostaCorretta: false },
    { id: "25193", argomento: "Aderenza", testo: "In motociclo, l'aderenza diminuisce sulle rotaie specialmente in caso di pioggia", immagine: "", rispostaCorretta: true },
    { id: "25194", argomento: "Aderenza", testo: "In motociclo, l'aderenza diminuisce sulla segnaletica orizzontale in caso di pioggia", immagine: "", rispostaCorretta: true },
    { id: "25195", argomento: "Aderenza", testo: "L'aderenza di un motociclo non dipende dal tipo di pavimentazione stradale", immagine: "", rispostaCorretta: false },
    { id: "25196", argomento: "Aderenza", testo: "L'aderenza di un motociclo diminuisce quando trasporta un passeggero", immagine: "", rispostaCorretta: false },
    { id: "25197", argomento: "Aderenza", testo: "La forza aderente diminuisce se la strada è sporca di olio", immagine: "", rispostaCorretta: true },
    { id: "25198", argomento: "Aderenza", testo: "La forza aderente risulta maggiore se l'asfalto è asciutto e pulito", immagine: "", rispostaCorretta: true },
    { id: "25199", argomento: "Aderenza", testo: "La forza aderente aumenta se l'asfalto è coperto di ghiaccio", immagine: "", rispostaCorretta: false },
    { id: "25200", argomento: "Aderenza", testo: "La forza aderente aumenta se l'asfalto è coperto dal fango", immagine: "", rispostaCorretta: false },
    { id: "25201", argomento: "Aderenza", testo: "La forza aderente non dipende dalla pressione dei pneumatici", immagine: "", rispostaCorretta: false },
    { id: "25202", argomento: "Stabilità", testo: "Percorrendo una curva, una forza tende a spostare il veicolo verso l'esterno", immagine: "", rispostaCorretta: true },
    { id: "25203", argomento: "Stabilità", testo: "In curva, la velocità eccessiva può provocare lo sbandamento del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25204", argomento: "Stabilità", testo: "In curva, la velocità eccessiva può provocare il ribaltamento del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25205", argomento: "Stabilità", testo: "In curva, una forza tende a spostare il veicolo verso l'interno", immagine: "", rispostaCorretta: false },
    { id: "25206", argomento: "Stabilità", testo: "In curva si deve aumentare la velocità per evitare lo slittamento", immagine: "", rispostaCorretta: false },
    { id: "25207", argomento: "Stabilità", testo: "In curva si deve aumentare la velocità per evitare il ribaltamento", immagine: "", rispostaCorretta: false },
    // --- BLOCCO: RESPONSABILITÀ E ASSICURAZIONE RCA (25007 - 25064) ---
    { id: "25007", argomento: "Assicurazione", testo: "L'assicurazione obbligatoria RCA copre i danni subiti dai terzi trasportati se il veicolo è autorizzato al trasporto di persone", immagine: "", rispostaCorretta: true },
    { id: "25008", argomento: "Assicurazione", testo: "L'assicurazione obbligatoria RCA copre i danni subiti da persone e/o cose in aree pubbliche o aperte al pubblico", immagine: "", rispostaCorretta: true },
    { id: "25009", argomento: "Assicurazione", testo: "Il risarcimento diretto si applica se vi sono danni al veicolo e lesioni di lieve entità al conducente", immagine: "", rispostaCorretta: true },
    { id: "25010", argomento: "Assicurazione", testo: "La procedura di risarcimento diretto non è applicabile se vi sono più di due veicoli coinvolti", immagine: "", rispostaCorretta: true },
    { id: "25011", argomento: "Assicurazione", testo: "Il risarcimento diretto è escluso se nel sinistro è coinvolto un motociclo", immagine: "", rispostaCorretta: false },
    { id: "25012", argomento: "Assicurazione", testo: "In caso di risarcimento diretto, la richiesta deve essere obbligatoriamente corredata di fotografie", immagine: "", rispostaCorretta: false },
    { id: "25014", argomento: "Responsabilità", testo: "La responsabilità civile per danni da circolazione è a carico del conducente e del proprietario del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25015", argomento: "Responsabilità", testo: "La responsabilità penale per danni da circolazione è a carico esclusivo del conducente", immagine: "", rispostaCorretta: true },
    { id: "25016", argomento: "Responsabilità", testo: "Il proprietario non è responsabile civilmente se prova che la circolazione è avvenuta contro la sua volontà", immagine: "", rispostaCorretta: true },
    { id: "25017", argomento: "Responsabilità", testo: "La responsabilità penale per danni connessi alla circolazione è a carico del proprietario del veicolo", immagine: "", rispostaCorretta: false },
    { id: "25019", argomento: "Assicurazione", testo: "È vietato utilizzare il veicolo privo di copertura assicurativa sulle strade pubbliche", immagine: "", rispostaCorretta: true },
    { id: "25020", argomento: "Assicurazione", testo: "Se l'assicurazione è scaduta, si incorre in sanzione sia circolando che lasciando il veicolo in sosta pubblica", immagine: "", rispostaCorretta: true },
    { id: "25021", argomento: "Assicurazione", testo: "Quando l'assicurazione RCA è scaduta si può incorrere nella confisca del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25024", argomento: "Assicurazione", testo: "Quando l'assicurazione RCA è scaduta è possibile lasciare il veicolo in sosta sulle strade pubbliche", immagine: "", rispostaCorretta: false },
    { id: "25027", argomento: "Assicurazione", testo: "Il 'Fondo di garanzia per le vittime della strada' risarcisce i danni alle persone causati da veicoli non assicurati", immagine: "", rispostaCorretta: true },
    { id: "25028", argomento: "Assicurazione", testo: "Il 'Fondo di garanzia per le vittime della strada' risarcisce i danni alle persone causati da veicoli non identificati", immagine: "", rispostaCorretta: true },
    { id: "25033", argomento: "Assicurazione", testo: "Le polizze per furto, incendio, atti vandalici o Kasko non sono obbligatorie", immagine: "", rispostaCorretta: true },
    { id: "25034", argomento: "Assicurazione", testo: "Nella polizza furto/incendio, il risarcimento non può superare il valore del veicolo al momento del danno", immagine: "", rispostaCorretta: true },
    { id: "25035", argomento: "Assicurazione", testo: "In caso di furto all'estero, bisogna ripetere la denuncia nello Stato italiano per attivare l'assicurazione", immagine: "", rispostaCorretta: true },
    { id: "25040", argomento: "Assicurazione", testo: "I massimali RCA sono gli importi massimi che l'assicurazione si impegna a pagare in caso di incidente", immagine: "", rispostaCorretta: true },
    { id: "25041", argomento: "Assicurazione", testo: "La cifra minima dei massimali della polizza RCA viene stabilita dalla legge", immagine: "", rispostaCorretta: true },
    { id: "25046", argomento: "Assicurazione", testo: "La formula 'bonus malus' comporta una variazione annuale del premio in base agli incidenti causati", immagine: "", rispostaCorretta: true },
    { id: "25050", argomento: "Assicurazione", testo: "L'assicurazione RCA è valida anche per gli incidenti avvenuti nei Paesi dell'Unione Europea", immagine: "", rispostaCorretta: true },
    { id: "25051", argomento: "Assicurazione", testo: "L'assicurazione RCA copre anche la responsabilità penale in base al premio pagato", immagine: "", rispostaCorretta: false },
    { id: "25057", argomento: "Assicurazione", testo: "Dopo la firma del contratto RCA, l'impresa deve rilasciare al cliente il certificato di assicurazione", immagine: "", rispostaCorretta: true },
    { id: "25060", argomento: "Assicurazione", testo: "Il certificato di assicurazione obbligatoria deve essere sempre tenuto a bordo del veicolo", immagine: "", rispostaCorretta: true },

    // --- BLOCCO: CONSUMI, RUMORE E AMBIENTE (25065 - 25107) ---
    { id: "25065", argomento: "Consumi", testo: "Gli apparecchi elettrici (radio, luci, lunotto termico) fanno aumentare i consumi di carburante", immagine: "", rispostaCorretta: true },
    { id: "25066", argomento: "Consumi", testo: "Mantenendo il più possibile costante la velocità, si riduce il consumo di carburante", immagine: "", rispostaCorretta: true },
    { id: "25067", argomento: "Consumi", testo: "Il consumo di carburante aumenta con l'aumentare del peso del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25069", argomento: "Consumi", testo: "Per consumare meno è opportuno tenere i finestrini chiusi, specie ad alta velocità", immagine: "", rispostaCorretta: true },
    { id: "25071", argomento: "Consumi", testo: "L'insufficiente pressione di gonfiaggio degli pneumatici comporta un maggior consumo di carburante", immagine: "", rispostaCorretta: true },
    { id: "25072", argomento: "Consumi", testo: "Collocare i bagagli sul tetto del veicolo comporta un maggior consumo di carburante", immagine: "", rispostaCorretta: true },
    { id: "25078", argomento: "Inquinamento Acustico", testo: "Per evitare rumori fastidiosi, occorre controllare che il silenziatore (marmitta) sia efficiente", immagine: "", rispostaCorretta: true },
    { id: "25079", argomento: "Inquinamento Acustico", testo: "L'inquinamento acustico aumenta se si usano in modo eccessivo clacson o trombe", immagine: "", rispostaCorretta: true },
    { id: "25081", argomento: "Inquinamento Acustico", testo: "Per evitare rumori non bisogna accelerare inutilmente e ripetutamente se il veicolo è fermo", immagine: "", rispostaCorretta: true },
    { id: "25082", argomento: "Inquinamento Acustico", testo: "Il clacson va usato solo per motivi di sicurezza stradale (pericolo immediato o trasporto feriti)", immagine: "", rispostaCorretta: true },
    { id: "25089", argomento: "Inquinamento Acustico", testo: "Per diminuire il rumore la marmitta deve essere efficiente e di tipo approvato", immagine: "", rispostaCorretta: true },
    { id: "25092", argomento: "Inquinamento Acustico", testo: "Bisogna far controllare i freni se emettono rumore durante la frenata per ridurre la rumorosità", immagine: "", rispostaCorretta: true },
    { id: "25095", argomento: "Inquinamento Acustico", testo: "Per diminuire il rumore è opportuno praticare dei fori nel dispositivo silenziatore (marmitta)", immagine: "", rispostaCorretta: false },
    { id: "25098", argomento: "Inquinamento Acustico", testo: "Nelle curve a forte velocità, lo strisciamento degli pneumatici aumenta la rumorosità del veicolo", immagine: "", rispostaCorretta: true },
    { id: "25100", argomento: "Inquinamento", testo: "Per diminuire l'inquinamento non bisogna accelerare bruscamente durante le partenze", immagine: "", rispostaCorretta: true },
    { id: "25101", argomento: "Inquinamento", testo: "Per diminuire l'inquinamento bisogna evitare di tenere inserita troppo a lungo una marcia bassa", immagine: "", rispostaCorretta: true },
    { id: "25102", argomento: "Inquinamento", testo: "Nei veicoli a scoppio, bisogna sostituire la marmitta catalitica quando è deteriorata o esausta", immagine: "", rispostaCorretta: true },
    { id: "25105", argomento: "Inquinamento", testo: "Per diminuire l'inquinamento dell'aria, bisogna ridurre la pressione di gonfiaggio degli pneumatici", immagine: "", rispostaCorretta: false },
    { id: "25107", argomento: "Inquinamento", testo: "Nei veicoli catalitici, l'inquinamento è minore subito dopo l'accensione, quando la temperatura è bassa", immagine: "", rispostaCorretta: false },
    // --- INTEGRAZIONE: DOMANDE MANCANTI ---

    // Assicurazione e Responsabilità
    { id: "25013", argomento: "Assicurazione", testo: "L'assicurazione obbligatoria copre i danni subiti solo da terzi trasportati sui taxi", immagine: "", rispostaCorretta: false },
    { id: "25018", argomento: "Responsabilità", testo: "La responsabilità per danni alla circolazione è a carico solo del conducente se ci sono danni alle cose", immagine: "", rispostaCorretta: false },
    { id: "25022", argomento: "Assicurazione", testo: "Quando l'assicurazione è scaduta si può continuare a usare il veicolo solo per brevi tragitti", immagine: "", rispostaCorretta: false },
    { id: "25023", argomento: "Assicurazione", testo: "Quando l'assicurazione è scaduta si può utilizzare il veicolo solo sul territorio italiano", immagine: "", rispostaCorretta: false },
    { id: "25025", argomento: "Assicurazione", testo: "Se l'assicurazione è scaduta, il veicolo deve subire un collaudo tecnico prima di circolare", immagine: "", rispostaCorretta: false },
    { id: "25026", argomento: "Assicurazione", testo: "Se l'assicurazione è scaduta, si può usare il veicolo se si pagano personalmente i danni", immagine: "", rispostaCorretta: false },
    { id: "25029", argomento: "Assicurazione", testo: "Il 'Fondo di garanzia per le vittime della strada' garantisce un vitalizio al conducente infortunato", immagine: "", rispostaCorretta: false },
    { id: "25032", argomento: "Assicurazione", testo: "Il 'Fondo di garanzia per le vittime della strada' risarcisce i danni arrecati dai conducenti minorenni", immagine: "", rispostaCorretta: false },
    
    // Altre Polizze e Dettagli
    { id: "25036", argomento: "Assicurazione", testo: "La polizza furto o incendio garantisce una rendita vitalizia al proprietario se il veicolo è rubato", immagine: "", rispostaCorretta: false },
    { id: "25039", argomento: "Assicurazione", testo: "Le polizze incendio coprono normalmente solo i danni da incendi dolosi e non quelli accidentali", immagine: "", rispostaCorretta: false },
    { id: "25043", argomento: "Assicurazione", testo: "I massimali della polizza RCA sono le somme che l'assicurazione riscuote ogni anno dal cliente", immagine: "", rispostaCorretta: false },
    { id: "25047", argomento: "Assicurazione", testo: "La formula assicurativa 'bonus malus' non si applica per i motocicli", immagine: "", rispostaCorretta: false },
    { id: "25052", argomento: "Assicurazione", testo: "L'assicurazione RCA copre anche le sanzioni amministrative pecuniarie previste dal codice della strada", immagine: "", rispostaCorretta: false },
    { id: "25055", argomento: "Assicurazione", testo: "L'assicurazione RCA copre solo i danni alle persone; per le cose serve un altro contratto", immagine: "", rispostaCorretta: false },
    { id: "25064", argomento: "Assicurazione", testo: "L'assicurazione obbligatoria RCA comprende il risarcimento danni solo se guida il proprietario", immagine: "", rispostaCorretta: false },

    // Consumi e Rumore (Dettagli)
    { id: "25073", argomento: "Consumi", testo: "Tenere aperto il tettuccio scorrevole del veicolo comporta un minor consumo di carburante", immagine: "", rispostaCorretta: false },
    { id: "25083", argomento: "Inquinamento Acustico", testo: "Nelle fermate per traffico, occorre mantenere il motore acceso accelerando ripetutamente", immagine: "", rispostaCorretta: false },
    { id: "25088", argomento: "Inquinamento Acustico", testo: "Il rumore prodotto dai veicoli a motore è causato solo dal motore", immagine: "", rispostaCorretta: false },
    { id: "25097", argomento: "Inquinamento Acustico", testo: "Per diminuire il rumore emesso dai veicoli basta eliminare la parte finale della marmitta", immagine: "", rispostaCorretta: false },
    { id: "25103", argomento: "Inquinamento", testo: "Per diminuire l'inquinamento dell'aria, bisogna controllare spesso la frizione e il differenziale", immagine: "", rispostaCorretta: false },
    { id: "25104", argomento: "Inquinamento", testo: "Per diminuire l'inquinamento dell'aria, bisogna controllare spesso gli ammortizzatori", immagine: "", rispostaCorretta: false },

    // Aderenza e Velocità
    { id: "25173", argomento: "Aderenza", testo: "La forza aderente, se eccessiva, comporta il surriscaldamento dei freni", immagine: "", rispostaCorretta: false },
    { id: "25184", argomento: "Aderenza", testo: "Se il coefficiente di aderenza è basso bisogna ridurre la velocità solo in curva", immagine: "", rispostaCorretta: false },
    { id: "25191", argomento: "Aderenza", testo: "Il coefficiente di aderenza basso diminuisce i consumi di carburante", immagine: "", rispostaCorretta: false },

    // --- BLOCCO: SICUREZZA, MASSE E VISIBILITÀ (23963 - 24010) ---
    { id: "23963", argomento: "Sicurezza e Visibilità", testo: "Il conducente di un'autovettura deve prestare particolare attenzione per la presenza di velocipedi utilizzati da giovani o anziani", immagine: "", rispostaCorretta: true },
    { id: "23964", argomento: "Sicurezza e Visibilità", testo: "Per un ciclista che effettua una manovra è molto difficile valutare la velocità dei veicoli a motore in avvicinamento", immagine: "", rispostaCorretta: true },
    { id: "23965", argomento: "Sicurezza e Visibilità", testo: "Il conducente deve prevedere la difficoltà del ciclista nel valutare la velocità dell'autovettura che sopraggiunge mentre lui svoltare a sinistra", immagine: "", rispostaCorretta: true },
    { id: "23966", argomento: "Sicurezza e Visibilità", testo: "Bisogna usare prudenza con ciclisti anziani che faticano a ruotare il busto per ispezionare la strada dietro di sé", immagine: "", rispostaCorretta: true },
    { id: "23967", argomento: "Sicurezza e Visibilità", testo: "La presenza di bambini in bicicletta in ambito extraurbano non rappresenta un rischio data la loro modesta velocità", immagine: "", rispostaCorretta: false },
    { id: "23968", argomento: "Sicurezza e Visibilità", testo: "I ciclisti viaggiano in sicurezza extraurbana perché i conducenti a motore prevedono sempre le loro cadute per fondo irregolare", immagine: "", rispostaCorretta: false },
    { id: "23969", argomento: "Sicurezza e Visibilità", testo: "La velocità di un'autovettura extraurbana è facilmente valutabile a distanza da un ciclista che procede lentamente", immagine: "", rispostaCorretta: false },
    { id: "23970", argomento: "Sicurezza e Visibilità", testo: "Il conducente deve ricordare il rischio dei ciclomotoristi giovani dotati di limitata esperienza di guida", immagine: "", rispostaCorretta: true },
    { id: "23971", argomento: "Sicurezza e Visibilità", testo: "La svolta a sinistra è pericolosa per un ciclomotore che interferisce con traiettorie di veicoli più veloci", immagine: "", rispostaCorretta: true },
    { id: "23972", argomento: "Sicurezza e Visibilità", testo: "Il conducente deve valutare con prudenza la distanza da un ciclomotorista che si accinge a svoltare", immagine: "", rispostaCorretta: true },
    { id: "23973", argomento: "Sicurezza e Visibilità", testo: "Il conducente deve prevedere manovre improvvise altrui, come il procedere a zig-zag di un ciclomotore", immagine: "", rispostaCorretta: true },
    { id: "23974", argomento: "Sicurezza e Visibilità", testo: "Bisogna rispettare la distanza di sicurezza laterale da ciclisti o ciclomotoristi per non comprometterne l'equilibrio", immagine: "", rispostaCorretta: true },
    { id: "23975", argomento: "Sicurezza e Visibilità", testo: "Bisogna evitare deviazioni trasversali del proprio veicolo in presenza di ciclisti o ciclomotoristi per evitarne la caduta", immagine: "", rispostaCorretta: true },
    { id: "23976", argomento: "Sicurezza e Visibilità", testo: "Il conducente non è tenuto a prevedere le possibili imprudenze del ciclomotorista che lo affianca", immagine: "", rispostaCorretta: false },
    { id: "23977", argomento: "Sicurezza e Visibilità", testo: "Risulta facile valutare la distanza da un ciclomotorista che rallenta bruscamente per svoltare in una strada mal segnalata", immagine: "", rispostaCorretta: false },
    { id: "23978", argomento: "Sicurezza e Visibilità", testo: "Un'autovettura può superare a velocità sostenuta un ciclomotorista nonostante la scarsa distanza laterale", immagine: "", rispostaCorretta: false },
    { id: "23979", argomento: "Sicurezza e Visibilità", testo: "Il conducente deve conoscere i rischi derivanti da mezzi molto lenti, come ciclomotori a tre ruote, su strade extraurbane", immagine: "", rispostaCorretta: true },
    { id: "23980", argomento: "Sicurezza e Visibilità", testo: "Su strada extraurbana, un ciclomotore a tre ruote è un potenziale pericolo se effettua manovre improvvise", immagine: "", rispostaCorretta: true },
    { id: "23981", argomento: "Sicurezza e Visibilità", testo: "Può risultare difficile valutare la velocità di una macchina agricola che procede lentamente su strada extraurbana", immagine: "", rispostaCorretta: true },
    { id: "23982", argomento: "Sicurezza e Visibilità", testo: "La presenza di veicoli con velocità molto diverse tra loro costituisce un fattore di sicurezza", immagine: "", rispostaCorretta: false },
    { id: "23983", argomento: "Sicurezza e Visibilità", testo: "Risulta facile valutare i tempi di avvicinamento a un veicolo lento quando si viaggia a velocità sostenuta", immagine: "", rispostaCorretta: false },
    { id: "23984", argomento: "Sicurezza e Visibilità", testo: "È maggiormente pericolosa la collisione tra veicoli dotati di masse molto diverse tra loro", immagine: "", rispostaCorretta: true },
    { id: "23985", argomento: "Sicurezza e Visibilità", testo: "Guidando una piccola vettura bisogna valutare i rischi di collisione con veicoli di massa superiore", immagine: "", rispostaCorretta: true },
    { id: "23986", argomento: "Sicurezza e Visibilità", testo: "Un'autovettura di notevole massa garantisce sicurezza anche per gli altri veicoli di massa inferiore", immagine: "", rispostaCorretta: false },
    { id: "23987", argomento: "Sicurezza e Visibilità", testo: "I veicoli sono tanto più sicuri quanto più le loro masse sono differenziate", immagine: "", rispostaCorretta: false },
    { id: "23988", argomento: "Sicurezza e Visibilità", testo: "Le grandi differenze di prestazioni e di masse fra le autovetture facilitano la sicurezza stradale", immagine: "", rispostaCorretta: false },
    { id: "23989", argomento: "Sicurezza e Visibilità", testo: "Il conducente di un SUV deve sapere che altezza e massa del mezzo sono un pericolo per utenti deboli e auto piccole", immagine: "", rispostaCorretta: true },
    { id: "23990", argomento: "Sicurezza e Visibilità", testo: "I conducenti di SUV devono considerare i gravi danni che i loro paraurti rinforzati possono causare a veicoli piccoli", immagine: "", rispostaCorretta: true },
    { id: "23991", argomento: "Sicurezza e Visibilità", testo: "La guida di un SUV è impegnativa in città e richiede cautele nelle manovre di emergenza", immagine: "", rispostaCorretta: true },
    { id: "23992", argomento: "Sicurezza e Visibilità", testo: "Un SUV garantisce la massima sicurezza per gli occupanti e per tutti gli altri utenti della strada", immagine: "", rispostaCorretta: false },
    { id: "23993", argomento: "Sicurezza e Visibilità", testo: "I paraurti sporgenti (bull bars) dei fuoristrada li rendono meno pericolosi per gli altri veicoli in caso di urto", immagine: "", rispostaCorretta: false },
    { id: "23994", argomento: "Sicurezza e Visibilità", testo: "La guida di un fuoristrada (SUV) risulta particolarmente indicata all'interno dei centri abitati", immagine: "", rispostaCorretta: false },
    { id: "23995", argomento: "Sicurezza e Visibilità", testo: "Bisogna valutare costantemente la pericolosità di autobus e mezzi industriali per la loro massa elevata", immagine: "", rispostaCorretta: true },
    { id: "23996", argomento: "Sicurezza e Visibilità", testo: "Bisogna saper valutare i rischi derivanti da mezzi pesanti che non rispettano i limiti di velocità", immagine: "", rispostaCorretta: true },
    { id: "23997", argomento: "Sicurezza e Visibilità", testo: "Autotreni e autoarticolati non costituiscono rischi maggiori rispetto a qualsiasi altro veicolo", immagine: "", rispostaCorretta: false },
    { id: "23998", argomento: "Sicurezza e Visibilità", testo: "Durante la guida il conducente deve visualizzare attentamente l'area antistante e limitrofa al veicolo", immagine: "", rispostaCorretta: true },
    { id: "23999", argomento: "Sicurezza e Visibilità", testo: "Il campo di visibilità può essere ridotto dai poggiatesta o dai montanti della carrozzeria", immagine: "", rispostaCorretta: true },
    { id: "24000", argomento: "Sicurezza e Visibilità", testo: "È vietato applicare pellicole adesive sul parabrezza e sui vetri laterali anteriori", immagine: "", rispostaCorretta: true },
    { id: "24001", argomento: "Sicurezza e Visibilità", testo: "Pedoni e bambini rischiano di restare fuori dal campo visivo di un SUV a causa delle dimensioni del mezzo", immagine: "", rispostaCorretta: true },
    { id: "24002", argomento: "Sicurezza e Visibilità", testo: "Il conducente può limitarsi a un controllo visivo affrettato se il mezzo ha per costruzione buona visibilità", immagine: "", rispostaCorretta: false },
    { id: "24003", argomento: "Sicurezza e Visibilità", testo: "È consentito applicare pellicole adesive sul parabrezza se sono di materiale rimovibile", immagine: "", rispostaCorretta: false },
    { id: "24004", argomento: "Sicurezza e Visibilità", testo: "I fuoristrada permettono la visibilità di tutti gli ostacoli bassi, come i bambini, grazie alla loro altezza", immagine: "", rispostaCorretta: false },
    { id: "24005", argomento: "Sicurezza e Visibilità", testo: "Prima di ripartire, un autocarro deve controllare la zona antistante per la possibile presenza di pedoni o ciclisti", immagine: "", rispostaCorretta: true },
    { id: "24006", argomento: "Sicurezza e Visibilità", testo: "Un autocarro fermo al semaforo deve prevedere pedoni o ciclisti nascosti dalla sagoma del veicolo", immagine: "", rispostaCorretta: true },
    { id: "24007", argomento: "Sicurezza e Visibilità", testo: "La scarsa visuale davanti agli autocarri rende pericolosa la fermata in colonna se sono presenti pedoni o bici", immagine: "", rispostaCorretta: true },
    { id: "24008", argomento: "Sicurezza e Visibilità", testo: "Il campo di visibilità degli autocarri permette il controllo sicuro di tutta la zona antistante e laterale", immagine: "", rispostaCorretta: false },
    { id: "24009", argomento: "Sicurezza e Visibilità", testo: "Un pedone può attraversare davanti a un autocarro fermo in colonna perché è sicuramente visibile dal conducente", immagine: "", rispostaCorretta: false },
    { id: "24010", argomento: "Sicurezza e Visibilità", testo: "I conducenti di autocarri che ripartono al semaforo avvistano facilmente chi affianca la parte anteriore del mezzo", immagine: "", rispostaCorretta: false }

];
